app:
  debug:
    debug_tasks: true
    debug_obs_remote: false
    debug_osc_conditions: true
    debug_osc_connection: false
#  store_persist_path: "/tmp/app-tmp/store.json"

obs_connections:
  - name: "streampc_obs"
    host: 192.168.2.118
    port: 4455
    password: "WoodenTableWithPineapple"


osc_sources:
  console_bridges:
  - name: "church_mixer_x32"
    enabled: true
    prefix: ""
    host: 192.168.2.99
    port: 10023
    osc_implementation: l
    init_command:
      address: /xinfo
#      arguments:
#        - type: string
#          value: "ok"
    check_address: /ch/01/mix/on
    check_pattern: "^0|1$"
    subscriptions:
      - osc_command:
          address: /subscribe
          arguments:
            - type: string
              value: /ch/01/mix/on
            - type: int32
              value: 10
        repeat_millis: 8000
      - osc_command:
          address: /subscribe
          arguments:
            - type: string
              value: /ch/02/mix/on
            - type: int32
              value: 10
        repeat_millis: 8000
      - osc_command:
          address: /subscribe
          arguments:
            - type: string
              value: /config/userrout/in/09
            - type: int32
              value: 10
        repeat_millis: 8000

#  tickers:
#    - name: "ticker1"
#      enabled: false
#      prefix: ""
#      refresh_rate_millis: 1000
#
#  http_bridges:
#    - name: "httpbridge1"
#      enabled: false
#      prefix: ""
#      port: 7878
#      host: 0.0.0.0

  obs_bridges:
    - name: "obsbridge1"
      enabled: true
      prefix: "" 
      connection: "streampc_obs"  


actions:
  change_to_pulpit:
    trigger_chain:
      type: and
      children:
        - type: osc_match
          parameters:
              address: /obs/program_scene
              arguments:
                - index: 0
                  type: "string"
                  value_match_type: "regexp"
                  value: ".*autoptz.*"
        - type: or
          children:
            - type: osc_match
              parameters:
                address: /ch/01/mix/on
                arguments:
                  - index: 0
                    type: "int32"
                    value: "1"
            - type: osc_match
              parameters:
                address: /ch/02/mix/on
                arguments:
                  - index: 0
                    type: "int32"
                    value: "1"
            - type: osc_match
              # stage mute (0: muted, 33 unmuted)"
              parameters:
                address: /config/userrout/in/09
                arguments:
                  - index: 0
                    type: "int32"
                    value: "0"

    tasks:
      - type: http_request
        parameters:
          url: "http://192.168.2.104/cgi-bin/ptzctrl.cgi?ptzcmd&poscall&0#PULPIT"
          method: "get"
          timeout_secs: 1
      - type: obs_scene_change
        parameters:
          scene: "^PULPIT($|\\s*.*)"
          scene_match_type: regexp
          target: "program"
          connection: "streampc_obs"



  change_to_stage:
    trigger_chain:
      type: and
      children:
        - type: osc_match
          parameters:
            address: /obs/program_scene
            arguments:
              - index: 0
                type: "string"
                value_match_type: "regexp"
                value: ".*autoptz.*"
        - type: osc_match
          parameters:
            address: /ch/01/mix/on
            arguments:
              - index: 0
                type: "int32"
                value: "0"
        - type: osc_match
          parameters:
            address: /ch/02/mix/on
            arguments:
              - index: 0
                type: "int32"
                value: "0"
        - type: osc_match
          # stage mute (0: muted, 33 unmuted)"
          parameters:
            address: /config/userrout/in/09
            arguments:
              - index: 0
                type: "int32"
                value: "33"

    tasks:
      - type: http_request
        parameters:
          url: "http://192.168.2.104/cgi-bin/ptzctrl.cgi?ptzcmd&poscall&1#STAGE"
          method: "get"
          timeout_secs: 1
      - type: obs_scene_change
        parameters:
          scene: "^STAGE($|\\s*.*)"
          scene_match_type: regexp
          target: "program"
          connection: "streampc_obs"

