@startuml
!theme mars
'skinparam linetype polyline
'skinparam linetype ortho
'left to right direction
skinparam style strictuml
hide empty members
skinparam groupInheritance 2


skin rose


title Signal Paths (NOT READY YET)

Object Channels {
    CH1 = Headset
    CH2 = Pulpit
    CH3 = Unused
    CH4 = Unused
    CH5 = Unused
    CH6 = Unused
    CH7 = Audience L
    CH8 = Audience R

    CH9 = Mic 1
    CH10 = Mic 2
    CH11 = Mic 3
    CH12 = Mic 4
    CH13 = Mic 5
    CH14 = Unused
    CH15 = DrumTB
    CH16 = Corner XLR

    CH17 = Instrument 1
    CH18 = Instrument 2
    CH19 = Instrument 3
    CH20 = Instrument 4
    CH21 = Keyboard L
    CH22 = Keyboard R
    CH23 = Unused
    CH24 = Click

    CH25 = Kick
    CH26 = Snare
    CH27 = Tom
    CH28 = Tom
    CH29 = Tom
    CH30 = Tom
    CH31 = Overhead L
    CH32 = Overhead R
}

Object Busses {
    Mix1 = Live L
    Mix2 = Live R
    Mix3 = Drum Mon
    Mix4 = Audience Gate Side Chain
    Mix5 = Drumroom talkback Side Chain
    Mix6 = Talkback
    Mix7 = Pulpit Feedback Fixer
    Mix8 = Guitar Mon
    Mix9 = Stage Feedback Fixer
    Mix10 = Mains Mon
    Mix11 =
    Mix12 =
    Mix13 = Effects input 1
    Mix14 = Effects input 2
    Mix15 = Effects input 3
    Mix16 = Effects input 4
}

Object P16 {
    CH1 = Mic1
    CH2 = Mic2
    CH3 = Mic3
    CH4 = Mic4
    CH5 = Mic5
    CH6 = Mic6 (Keys)
    CH7 = Inst1
    CH8 = Inst2
    CH9 = Inst3
    CH10 = Inst4
    CH11 = Inst5
    CH12 = Keys
    CH13 = Mains
    CH14 = Talkback
    CH15 = Drums
    CH16 =
}

Channels::CH9 ---> P16::CH1
Channels::CH10 ---> P16::CH2
Channels::CH11 ---> P16::CH3
Channels::CH12 ---> P16::CH4
Busses::Mix8 ---> P16::CH5
Channels::CH19 ---> P16::CH6
Channels::CH21 ---> P16::CH7
Busses::Mix3 ---> P16::CH8
Channels::CH20 ---> P16::CH9
Busses::Mix10 ---> P16::CH10
Busses::Mix6 ---> P16::CH11

Channels::CH13 ---> P16::CH13
Channels::CH14 ---> P16::CH14
Channels::CH9 ---> P16::CH15
Channels::CH9 ---> P16::CH16

Object LR

Channels::CH1 ---> LR
Channels::CH1 ---> Busses::Mix1
Channels::CH1 ---> Busses::Mix2

Channels::CH2 ---> Busses::Mix7
Channels::CH2 ---> Busses::Mix1
Channels::CH2 ---> Busses::Mix2

Channels::CH7 ---> Busses::Mix1
Channels::CH8 ---> Busses::Mix2


Channels::CH9 ---> LR
Channels::CH9 ---> Busses::Mix1
Channels::CH9 ---> Busses::Mix2
Channels::CH9 ---> Busses::Mix13
Channels::CH9 ---> Busses::Mix14
Channels::CH9 ---> Busses::Mix15
Channels::CH9 ---> Busses::Mix16

Channels::CH10 ---> LR
Channels::CH10 ---> Busses::Mix1
Channels::CH10 ---> Busses::Mix2
Channels::CH10 ---> Busses::Mix13
Channels::CH10 ---> Busses::Mix14
Channels::CH10 ---> Busses::Mix15
Channels::CH10 ---> Busses::Mix16


Channels::CH11 ---> LR
Channels::CH11 ---> Busses::Mix1
Channels::CH11 ---> Busses::Mix2
Channels::CH11 ---> Busses::Mix13
Channels::CH11 ---> Busses::Mix14
Channels::CH11 ---> Busses::Mix15
Channels::CH11 ---> Busses::Mix16


Channels::CH12 ---> LR
Channels::CH12 ---> Busses::Mix1
Channels::CH12 ---> Busses::Mix2
Channels::CH12 ---> Busses::Mix13
Channels::CH12 ---> Busses::Mix14
Channels::CH12 ---> Busses::Mix15
Channels::CH12 ---> Busses::Mix16


Channels::CH13 ---> LR
Channels::CH13 ---> Busses::Mix1
Channels::CH13 ---> Busses::Mix2
Channels::CH13 ---> Busses::Mix13
Channels::CH13 ---> Busses::Mix14
Channels::CH13 ---> Busses::Mix15
Channels::CH13 ---> Busses::Mix16


Channels::CH17 ---> LR
Channels::CH17 ---> Busses::Mix1
Channels::CH17 ---> Busses::Mix2

Channels::CH18 ---> LR
Channels::CH18 ---> Busses::Mix1
Channels::CH18 ---> Busses::Mix2

Channels::CH19 ---> LR
Channels::CH19 ---> Busses::Mix1
Channels::CH19 ---> Busses::Mix2

Channels::CH20 ---> LR
Channels::CH20 ---> Busses::Mix1
Channels::CH20 ---> Busses::Mix2

Channels::CH21 ---> LR
Channels::CH21 ---> Busses::Mix1
Channels::CH21 ---> Busses::Mix2

Channels::CH22 ---> LR
Channels::CH22 ---> Busses::Mix1
Channels::CH22 ---> Busses::Mix2

Channels::CH26 ---> LR
Channels::CH26 ---> Busses::Mix1
Channels::CH26 ---> Busses::Mix2

Channels::CH27 ---> LR
Channels::CH27 ---> Busses::Mix1
Channels::CH27 ---> Busses::Mix2

Channels::CH28 ---> LR
Channels::CH28 ---> Busses::Mix1
Channels::CH28 ---> Busses::Mix2

Channels::CH29 ---> LR
Channels::CH29 ---> Busses::Mix1
Channels::CH29 ---> Busses::Mix2

Channels::CH30 ---> LR
Channels::CH30 ---> Busses::Mix1
Channels::CH30 ---> Busses::Mix2

Channels::CH31 ---> LR
Channels::CH31 ---> Busses::Mix1
Channels::CH31 ---> Busses::Mix2

Channels::CH32 ---> LR
Channels::CH32 ---> Busses::Mix1
Channels::CH32 ---> Busses::Mix2



Busses::Mix7 ---> LR

Object Matrix {
    Mtx1 = Front L
    Mtx2 = Front R
    Mtx3 = Fill L
    Mtx4 = Fill R
    Mtx5 = Coffee Shop
    Mtx6 = Outside
}

LR ---> Matrix::Mtx1
LR ---> Matrix::Mtx2
LR ---> Matrix::Mtx3
LR ---> Matrix::Mtx4
LR ---> Matrix::Mtx5

@enduml
